-- Sync DocPro onboarding RFI fields: payer portal logins + expanded document types

ALTER TABLE "onboarding_credentialing"
ADD COLUMN IF NOT EXISTS "payer_portal_logins" JSONB;

ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'VOID_CHECK';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'BANK_ACCOUNT_LETTER';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'IRS_LETTER_147C';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'IN_NETWORK_INSURANCE_ROSTER';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'INSURANCE_ENROLLMENT_LIST';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'BOARD_CERTIFICATION';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'PLI';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'DRIVER_LICENSE';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'SOCIAL_SECURITY_CARD';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'PASSPORT_SIZED_PHOTO';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'RESUME_CV';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'BACHELOR_DEGREE';
ALTER TYPE "DocumentTypes" ADD VALUE IF NOT EXISTS 'MASTER_DEGREE';
